service: todoAPI
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:${aws:accountId}:table/*"

functions:
  createTodo:
    handler: src/createTodo.create_todo
    events:
      - httpApi:
          path: /todo
          method: post
  getTodo:
    handler: src/getTodo.get_todo
    events:
      - httpApi:
          path: /todo/{userId}
          method: get
  updateTodo:
    handler: src/updateTodo.update_todo
    events:
      - httpApi:
          path: /todo/{userId}
          method: put
  deleteTodo:
    handler: src/deleteTodo.delete_todo
    events:
      - httpApi:
          path: /todo/{userId}
          method: delete

resources:
  Resources:
    todoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoId
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: userId 
            AttributeType: S 
          - AttributeName: todoId 
            AttributeType: S 
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        
plugins:
  - serverless-python-requirements
